server:
  port: ${port:8080}

spring:
  application:
    name: eshop-eureka-service-01

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://root:root@127.0.0.1:8080/eureka/

security:
  basic:
    enabled: true
  user:
    name: root
    password: root
